/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary;

import Controller.Bobot_Manager;
import Controller.Gambar_Manager;
import Controller.CNN_Manager;
import Controller.Praproses_Manager;
import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandesign__
 */
public class FER_CNN extends javax.swing.JFrame {

    /**
     * Creates new form FER_CNN
     */
    private String direktori, lokasi, image[], nama,lokTst;
    private BufferedImage gambar, gambarGray;
    private int[][] input;
    private int lbl;
    private File file;
    private File files_selected=null;
    DefaultTableModel tabmod;
    String values ="";
    
    JFileChooser unggah;
    Gambar_Manager gm;
    Praproses_Manager pm;
    CNN_Manager im;
    Bobot_Manager bm;
    private int lok;
    JFileChooser unggah_file;
    
    
    public FER_CNN() {
        initComponents();
        unggah_file = new JFileChooser("D:\\NewFER");
        gm = new Gambar_Manager();
        pm = new Praproses_Manager();
        im = new CNN_Manager();
        bm = new Bobot_Manager();
        input = new int[32][32];
        labelTabTrain.setForeground(new Color(255,204,102));
        labelTabPengujian.setForeground(new Color (204,204,204));
        
//        btn_praprosesTrain.setEnabled(false);
//        btn_Pelatihan.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        side_menu = new javax.swing.JPanel();
        btn_train = new javax.swing.JPanel();
        labelTabTrain = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_pengujian = new javax.swing.JPanel();
        labelTabPengujian = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_kembaliTrain = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        panel_pelatihan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_unggah = new javax.swing.JButton();
        card_input = new javax.swing.JPanel();
        lblUnggahTrain = new javax.swing.JLabel();
        lable_show = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_file = new javax.swing.JTable();
        train_config = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        learning_rate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        epoch_max = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btn_praprosesTrain = new javax.swing.JButton();
        btn_Pelatihan = new javax.swing.JButton();
        indikator = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_pengujian = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_unggahTest = new javax.swing.JButton();
        card_input1 = new javax.swing.JPanel();
        lblUnggahTest = new javax.swing.JLabel();
        label_imageTest = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_inputTest = new javax.swing.JTable();
        train_config1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        hasilTest = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btn_PraprosesTest = new javax.swing.JButton();
        btn_Kenali = new javax.swing.JButton();
        indikatorTest = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pengenalan Ekspresi Wajah Manusia");
        setName("MainFrame"); // NOI18N
        setResizable(false);

        side_menu.setBackground(new java.awt.Color(29, 60, 94));
        side_menu.setPreferredSize(new java.awt.Dimension(281, 580));
        side_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_train.setBackground(new java.awt.Color(27, 55, 87));
        btn_train.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_train.setPreferredSize(new java.awt.Dimension(281, 50));
        btn_train.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_trainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_trainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_trainMouseExited(evt);
            }
        });

        labelTabTrain.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelTabTrain.setForeground(new java.awt.Color(204, 204, 204));
        labelTabTrain.setText("Pelatihan");
        labelTabTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTabTrainMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_eye_20px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn_trainLayout = new javax.swing.GroupLayout(btn_train);
        btn_train.setLayout(btn_trainLayout);
        btn_trainLayout.setHorizontalGroup(
            btn_trainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_trainLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(labelTabTrain)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        btn_trainLayout.setVerticalGroup(
            btn_trainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_trainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_trainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTabTrain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_menu.add(btn_train, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 50));

        btn_pengujian.setBackground(new java.awt.Color(29, 60, 94));
        btn_pengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengujian.setPreferredSize(new java.awt.Dimension(281, 50));
        btn_pengujian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengujianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pengujianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pengujianMouseExited(evt);
            }
        });

        labelTabPengujian.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelTabPengujian.setForeground(new java.awt.Color(204, 204, 204));
        labelTabPengujian.setText("Pengujian");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_eye_20px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn_pengujianLayout = new javax.swing.GroupLayout(btn_pengujian);
        btn_pengujian.setLayout(btn_pengujianLayout);
        btn_pengujianLayout.setHorizontalGroup(
            btn_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pengujianLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addComponent(labelTabPengujian)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        btn_pengujianLayout.setVerticalGroup(
            btn_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pengujianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(labelTabPengujian))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        side_menu.add(btn_pengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_sad_face_60px.png"))); // NOI18N
        side_menu.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Recognition");
        side_menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Facial Expression");
        side_menu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        side_menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 40));

        btn_kembaliTrain.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_kembaliTrain.setForeground(new java.awt.Color(204, 204, 204));
        btn_kembaliTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_back_20px_1.png"))); // NOI18N
        btn_kembaliTrain.setText("Kembali");
        btn_kembaliTrain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kembaliTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliTrainMouseClicked(evt);
            }
        });
        side_menu.add(btn_kembaliTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 70, -1));

        main_panel.setPreferredSize(new java.awt.Dimension(613, 600));
        main_panel.setLayout(new java.awt.CardLayout());

        panel_pelatihan.setBackground(new java.awt.Color(241, 239, 239));
        panel_pelatihan.setPreferredSize(new java.awt.Dimension(613, 600));

        jPanel1.setBackground(new java.awt.Color(29, 60, 94));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Panel Pelatihan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("|");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Pilih folder gambar pengujian terlebih dahulu");

        btn_unggah.setBackground(new java.awt.Color(255, 255, 255));
        btn_unggah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_search_folder_25px_1.png"))); // NOI18N
        btn_unggah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unggahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(65, 65, 65)
                .addComponent(btn_unggah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_unggah)
                        .addContainerGap())))
        );

        card_input.setLayout(new java.awt.CardLayout());

        lblUnggahTrain.setBackground(new java.awt.Color(255, 255, 255));
        lblUnggahTrain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnggahTrain.setForeground(new java.awt.Color(29, 60, 94));
        lblUnggahTrain.setOpaque(true);
        card_input.add(lblUnggahTrain, "card2");

        lable_show.setBackground(new java.awt.Color(255, 255, 255));
        lable_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_person_75px_2.png"))); // NOI18N
        lable_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lable_show.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(29, 60, 94));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Preview Image");
        jLabel13.setOpaque(true);

        table_file.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Nama File"
            }
        ));
        table_file.setFocusable(false);
        table_file.setGridColor(new java.awt.Color(255, 255, 255));
        table_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_fileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_file);
        if (table_file.getColumnModel().getColumnCount() > 0) {
            table_file.getColumnModel().getColumn(0).setMinWidth(30);
            table_file.getColumnModel().getColumn(0).setPreferredWidth(30);
            table_file.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        train_config.setLayout(new javax.swing.BoxLayout(train_config, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        learning_rate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        learning_rate.setForeground(new java.awt.Color(51, 51, 51));
        learning_rate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        learning_rate.setText("0.05");
        learning_rate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        learning_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learning_rateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Epoch");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Learning Rate");

        epoch_max.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        epoch_max.setForeground(new java.awt.Color(51, 51, 51));
        epoch_max.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        epoch_max.setText("10");
        epoch_max.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        epoch_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epoch_maxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(learning_rate, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(epoch_max))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epoch_max, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(learning_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        jPanel6.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btn_praprosesTrain.setBackground(new java.awt.Color(255, 255, 255));
        btn_praprosesTrain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_praprosesTrain.setForeground(new java.awt.Color(51, 51, 51));
        btn_praprosesTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_process_25px.png"))); // NOI18N
        btn_praprosesTrain.setText("Praproses");
        btn_praprosesTrain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_praprosesTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_praprosesTrainMousePressed(evt);
            }
        });
        btn_praprosesTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_praprosesTrainActionPerformed(evt);
            }
        });

        btn_Pelatihan.setBackground(new java.awt.Color(255, 255, 255));
        btn_Pelatihan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_Pelatihan.setForeground(new java.awt.Color(51, 51, 51));
        btn_Pelatihan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_play_25px.png"))); // NOI18N
        btn_Pelatihan.setText("Pelatihan");
        btn_Pelatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Pelatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PelatihanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PelatihanMousePressed(evt);
            }
        });
        btn_Pelatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PelatihanActionPerformed(evt);
            }
        });

        indikator.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        indikator.setForeground(new java.awt.Color(51, 51, 51));
        indikator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indikator.setText("....");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_praprosesTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Pelatihan, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(indikator)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Pelatihan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_praprosesTrain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indikator)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        train_config.add(jPanel3);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Pengenalan Ekspresi Wajah Manusia Menggunakan Metode Convolutional Neural Network");

        javax.swing.GroupLayout panel_pelatihanLayout = new javax.swing.GroupLayout(panel_pelatihan);
        panel_pelatihan.setLayout(panel_pelatihanLayout);
        panel_pelatihanLayout.setHorizontalGroup(
            panel_pelatihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(train_config, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_pelatihanLayout.createSequentialGroup()
                .addGroup(panel_pelatihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pelatihanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pelatihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lable_show, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_pelatihanLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pelatihanLayout.setVerticalGroup(
            panel_pelatihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pelatihanLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card_input, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_pelatihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_pelatihanLayout.createSequentialGroup()
                        .addComponent(lable_show, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(train_config, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main_panel.add(panel_pelatihan, "card2");

        panel_pengujian.setBackground(new java.awt.Color(241, 239, 239));
        panel_pengujian.setPreferredSize(new java.awt.Dimension(613, 580));

        jPanel8.setBackground(new java.awt.Color(29, 60, 94));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Panel Pengujian");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("|");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Pilih folder gambar pengujian terlebih dahulu");

        btn_unggahTest.setBackground(new java.awt.Color(255, 255, 255));
        btn_unggahTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_search_folder_25px_1.png"))); // NOI18N
        btn_unggahTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_unggahTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unggahTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(65, 65, 65)
                .addComponent(btn_unggahTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(btn_unggahTest)
                        .addContainerGap())))
        );

        card_input1.setLayout(new java.awt.CardLayout());

        lblUnggahTest.setBackground(new java.awt.Color(255, 255, 255));
        lblUnggahTest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnggahTest.setForeground(new java.awt.Color(29, 60, 94));
        lblUnggahTest.setOpaque(true);
        card_input1.add(lblUnggahTest, "card2");

        label_imageTest.setBackground(new java.awt.Color(255, 255, 255));
        label_imageTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_imageTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_person_75px_2.png"))); // NOI18N
        label_imageTest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        label_imageTest.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(29, 60, 94));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Preview Image");
        jLabel21.setOpaque(true);

        table_inputTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Nama File"
            }
        ));
        table_inputTest.setFocusable(false);
        table_inputTest.setGridColor(new java.awt.Color(255, 255, 255));
        table_inputTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_inputTestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_inputTest);

        train_config1.setLayout(new javax.swing.BoxLayout(train_config1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(29, 60, 94));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Hasil Pengenalan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        hasilTest.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        hasilTest.setForeground(new java.awt.Color(29, 60, 94));
        hasilTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hasilTest.setText("....");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasilTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(hasilTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        btn_PraprosesTest.setBackground(new java.awt.Color(255, 255, 255));
        btn_PraprosesTest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_PraprosesTest.setForeground(new java.awt.Color(51, 51, 51));
        btn_PraprosesTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_process_25px.png"))); // NOI18N
        btn_PraprosesTest.setText("Praproses");
        btn_PraprosesTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_PraprosesTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PraprosesTestMousePressed(evt);
            }
        });
        btn_PraprosesTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PraprosesTestActionPerformed(evt);
            }
        });

        btn_Kenali.setBackground(new java.awt.Color(255, 255, 255));
        btn_Kenali.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_Kenali.setForeground(new java.awt.Color(51, 51, 51));
        btn_Kenali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/img/icons8_play_25px.png"))); // NOI18N
        btn_Kenali.setText("Kenali");
        btn_Kenali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Kenali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_KenaliMousePressed(evt);
            }
        });
        btn_Kenali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KenaliActionPerformed(evt);
            }
        });

        indikatorTest.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        indikatorTest.setForeground(new java.awt.Color(51, 51, 51));
        indikatorTest.setText("...");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(indikatorTest)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btn_PraprosesTest, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Kenali, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Kenali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_PraprosesTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indikatorTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11, java.awt.BorderLayout.CENTER);

        train_config1.add(jPanel9);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Pengenalan Ekspresi Wajah Manusia Menggunakan Metode Convolutional Neural Network");

        javax.swing.GroupLayout panel_pengujianLayout = new javax.swing.GroupLayout(panel_pengujian);
        panel_pengujian.setLayout(panel_pengujianLayout);
        panel_pengujianLayout.setHorizontalGroup(
            panel_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_input1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(train_config1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_pengujianLayout.createSequentialGroup()
                .addGroup(panel_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pengujianLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_imageTest, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_pengujianLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pengujianLayout.setVerticalGroup(
            panel_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pengujianLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_pengujianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_pengujianLayout.createSequentialGroup()
                        .addComponent(label_imageTest, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(train_config1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main_panel.add(panel_pengujian, "card2");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(side_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(side_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trainMouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        btn_pengujian.setBackground(new Color(29,60,94));
        btn_train.setBackground(new Color(27,55,87));
        
        main_panel.add(panel_pelatihan);
        main_panel.repaint();
        main_panel.revalidate();
        labelTabTrain.setForeground(new Color(255,204,102));
        labelTabPengujian.setForeground(new Color (204,204,204));
        
    }//GEN-LAST:event_btn_trainMouseClicked

    private void labelTabTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTabTrainMouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(panel_pelatihan);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_labelTabTrainMouseClicked

    private void btn_pengujianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengujianMouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        btn_train.setBackground(new Color(29,60,94));
        btn_pengujian.setBackground(new Color(27,55,87));
        
        main_panel.add(panel_pengujian);
        main_panel.repaint();
        main_panel.revalidate();
        labelTabPengujian.setForeground(new Color (255,204,102));
        labelTabTrain.setForeground(new Color (204,204,204));
        
        
    }//GEN-LAST:event_btn_pengujianMouseClicked

    private void btn_unggahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unggahActionPerformed
        // TODO add your handling code here:
        unggah_file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int lok = unggah_file.showOpenDialog(FER_CNN.this);
        if(lok == JFileChooser.APPROVE_OPTION){
            direktori = unggah_file.getSelectedFile().getAbsolutePath();
            try {
                Object []baris = {"No","Nama File"};
                tabmod = new DefaultTableModel(null,baris);
                table_file.setModel(tabmod);
                File loc = new File (direktori);
                if(loc.isDirectory()){
                    int i=0;
                    for(File f:loc.listFiles()){
                        String nameFile = f.getName();
                        //System.out.println(f.getPath());
                        String[] fileIn = {Integer.toString(i+1),nameFile};
                        tabmod.addRow(fileIn);
                        i++;
                    }
                }
                gm.setDirektori_Train(direktori);
            } catch (IOException ex) {
                Logger.getLogger(FER_CNN.class.getName()).log(Level.SEVERE, null, ex);
            }
            lokasi = gm.getDirektori_Train();
            lblUnggahTrain.setText("   "+lokasi);
            btn_praprosesTrain.setEnabled(true);
        }
        

    }//GEN-LAST:event_btn_unggahActionPerformed
    
    public void kliktable(){
        String val;
        int baris = table_file.getSelectedRow();
        val =(String) table_file.getValueAt(baris,1);
        //System.out.println(val);
        ImageIcon ic = new ImageIcon(direktori+"\\"+val);
        Rectangle r = lable_show.getBounds();
        Image img = ic.getImage().getScaledInstance(r.width, r.height, Image.SCALE_DEFAULT);
        ic = new ImageIcon(img);
        lable_show.setIcon(ic);
    }
    public void kliktableTest() throws IOException{
        String val;
        int baris = table_inputTest.getSelectedRow();
        val =(String) table_inputTest.getValueAt(baris,1);
        //System.out.println(val);
        
        ImageIcon ic = new ImageIcon(val);
        Rectangle r = lable_show.getBounds();
        Image img = ic.getImage().getScaledInstance(r.width, r.height, Image.SCALE_DEFAULT);
        ic = new ImageIcon(img);
        label_imageTest.setIcon(ic);
        int value = table_inputTest.getSelectedRow();
        values = (String) table_inputTest.getValueAt(value, 1);
        System.out.println(values);
        file= new File(values);
        gm.loadImage_Test(file);
        gambar = gm.getImage_Test();
    }
    
    private void btn_unggahTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unggahTestActionPerformed
        // TODO add your handling code here:
        unggah_file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int lok = unggah_file.showOpenDialog(FER_CNN.this);
        if(lok == JFileChooser.APPROVE_OPTION){
            direktori = unggah_file.getSelectedFile().getAbsolutePath();

                Object []baris = {"No","Nama File"};
                tabmod = new DefaultTableModel(null,baris);
                table_inputTest.setModel(tabmod);
                File loc = new File (direktori);
                if(loc.isDirectory()){
                    int i=0;
                    for(File f:loc.listFiles()){
                        String nameFile = f.getPath();
                        //System.out.println(f.getPath());
                        String[] fileIn = {Integer.toString(i+1),nameFile};
                        tabmod.addRow(fileIn);
                        i++;
                    }
                }
            lokasi = gm.getDirektori_Train();
            lblUnggahTest.setText("   "+direktori);
            btn_praprosesTrain.setEnabled(true);
        }
        
        
        
    }//GEN-LAST:event_btn_unggahTestActionPerformed

    private void btn_KenaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KenaliActionPerformed
        // TODO add your handling code here:
         try {
            gambar = pm.set_Resize(gambar, 32, 32);
            input = gm.inputTesting(gambar);
            im.ReadupdateBobotBias();
            im.testing(input);
            String prediksi = im.getEkspresi();
            hasilTest.setText(prediksi);
          
        } catch (IOException ex) {
            Logger.getLogger(FER_CNN.class.getName()).log(Level.SEVERE, null, ex);
        }
         indikatorTest.setText("Pengenalan selesai....");
    }//GEN-LAST:event_btn_KenaliActionPerformed

    private void table_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_fileMouseClicked
        // TODO add your handling code here:
        kliktable();
        
    }//GEN-LAST:event_table_fileMouseClicked

    private void btn_praprosesTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_praprosesTrainActionPerformed
        // TODO add your handling code here:
        indikator.setText("Praproses sedang berjalan....");
        int i=0;
        File lok = new File(direktori);
        if(lok.isDirectory()){
            for(File f:lok.listFiles()){
                try {
                    gambar = ImageIO.read(f);
                    pm.binary(gambar);
                    
                    ImageIO.write(gambar,"JPG", new File("D:/NewFER/data latih/praproses/"+(i+1)+".jpg"));
                } catch (Exception e) {
                }i++;
            }
        }
        try {
            gm.deteksiTrain();
        } catch (Exception e) {
        }
        indikator.setText("Praproses selasai....");
        btn_Pelatihan.setEnabled(true);
    }//GEN-LAST:event_btn_praprosesTrainActionPerformed

    private void btn_kembaliTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliTrainMouseClicked
        // TODO add your handling code here:
        new MainForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_kembaliTrainMouseClicked

    private void btn_PelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PelatihanActionPerformed
        // TODO add your handling code here:
        try {
            bm.setBobotBias_Random();
            gm.resizeImage();
            im.training(this);
            JOptionPane.showMessageDialog(null, "Training Selesai");
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btn_PelatihanActionPerformed

    private void btn_PelatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PelatihanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_PelatihanMouseClicked

    private void btn_PelatihanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PelatihanMousePressed
        // TODO add your handling code here:
        indikator.setText("Pelatihan sedang berjalan....");
    }//GEN-LAST:event_btn_PelatihanMousePressed

    private void btn_praprosesTrainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_praprosesTrainMousePressed
        // TODO add your handling code here:
        indikator.setText("Praproses sedang berjalan....");
    }//GEN-LAST:event_btn_praprosesTrainMousePressed

    private void table_inputTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_inputTestMouseClicked
        try {
            // TODO add your handling code here:
            kliktableTest();
            hasilTest.setText("....");
            indikatorTest.setText("....");
        } catch (IOException ex) {
            Logger.getLogger(FER_CNN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_inputTestMouseClicked

    private void btn_PraprosesTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PraprosesTestActionPerformed
        // TODO add your handling code here:
        try {
            pm.binary(gambar);
            gambarGray = pm.getBinary();
            ImageIO.write(gambarGray, "JPG", new File("D:/NewFER/data uji/praproses.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(FER_CNN.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            gm.deteksiTest();
            gambar = ImageIO.read(Files.newInputStream(Paths.get(gm.gambarDeteksiTest())));
        } catch (IOException ex) {
            Logger.getLogger(FER_CNN.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icDeteksi = new ImageIcon(gambar);
        Rectangle rec = label_imageTest.getBounds();
        Image in = icDeteksi.getImage().getScaledInstance(rec.width, rec.height, Image.SCALE_DEFAULT);
        icDeteksi = new ImageIcon(in);
        label_imageTest.setIcon(icDeteksi);
        indikatorTest.setText("Praproses selesai....");
    }//GEN-LAST:event_btn_PraprosesTestActionPerformed

    private void btn_PraprosesTestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PraprosesTestMousePressed
        // TODO add your handling code here:
        indikatorTest.setText("Praproses sedang berjalan....");
    }//GEN-LAST:event_btn_PraprosesTestMousePressed

    private void btn_KenaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_KenaliMousePressed
        // TODO add your handling code here:
        indikatorTest.setText("Pegenalan sedang berjalan....");
    }//GEN-LAST:event_btn_KenaliMousePressed

    private void btn_trainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_trainMouseEntered

    private void btn_pengujianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengujianMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pengujianMouseEntered

    private void btn_pengujianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengujianMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pengujianMouseExited

    private void btn_trainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trainMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_trainMouseExited

    private void epoch_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epoch_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epoch_maxActionPerformed

    private void learning_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learning_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_learning_rateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FER_CNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FER_CNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FER_CNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FER_CNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FER_CNN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_Kenali;
    private javax.swing.JButton btn_Pelatihan;
    private javax.swing.JButton btn_PraprosesTest;
    private javax.swing.JLabel btn_kembaliTrain;
    private javax.swing.JPanel btn_pengujian;
    private javax.swing.JButton btn_praprosesTrain;
    private javax.swing.JPanel btn_train;
    private javax.swing.JButton btn_unggah;
    private javax.swing.JButton btn_unggahTest;
    private javax.swing.JPanel card_input;
    private javax.swing.JPanel card_input1;
    public javax.swing.JTextField epoch_max;
    private javax.swing.JLabel hasilTest;
    private javax.swing.JLabel icon;
    public javax.swing.JLabel indikator;
    private javax.swing.JLabel indikatorTest;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelTabPengujian;
    private javax.swing.JLabel labelTabTrain;
    private javax.swing.JLabel label_imageTest;
    private javax.swing.JLabel lable_show;
    private javax.swing.JLabel lblUnggahTest;
    private javax.swing.JLabel lblUnggahTrain;
    public javax.swing.JTextField learning_rate;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel panel_pelatihan;
    private javax.swing.JPanel panel_pengujian;
    private javax.swing.JPanel side_menu;
    public javax.swing.JTable table_file;
    public javax.swing.JTable table_inputTest;
    private javax.swing.JPanel train_config;
    private javax.swing.JPanel train_config1;
    // End of variables declaration//GEN-END:variables
}
